api_version = "2025-07"

[[extensions]]
name = "thank-you-survey"
handle = "thank-you-survey"
type = "ui_extension"
uid = "36589f62-9892-39cb-2f34-f27a46d18b634b74a298"


[[extensions.targeting]]
module = "./src/index.tsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
api_access = true
network_access = true

[[extensions.metafields]]
namespace = "zenloop"
key = "settings"
