# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a3527c5839cad1d7c7b15e164f00dba"
name = "zenloop-surveys-dev"
application_url = "https://zenloop-survey-plugin-xn48.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "steve-zenloop-test3.myshopify.com"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact",
]
uri = "/webhooks/gdpr"
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_checkouts,write_products"

[auth]
redirect_urls = ["https://example.com/api/auth"]

# ?prevent_order_redirect=true
